### ISSUE TITLE
Wrong scaling of the spherical cap .stl

### ISSUE THREAD

**Issue by KevinStrobel** [asiermarzo/Ultraino#1]
When the file from:
https://github.com/asiermarzo/Ultraino/blob/master/arrays/spherical%20cap.STL

is imported into FreeCAD or Ultimaker Cura the model is 25 times smaller than it should be, 
for the 1cm transducers to fit into their places.

I was wondering, if this is due to an import error or if the .stl has a false scaling.

Best regards, 
Kevin

**Comment by asiermarzo** [comment]
Hi kevin,
I apologize some the STLs still use strange scaling due to inch/mm.
The factor is 25.4 I have updated the STL file.
Thanks for the notice.
Best,
Asier.

**Comment by KevinStrobel** [comment]
Hy Asier,

Thank you for the quick response. The updated .stl is now scaled correctly in Cura.

Best regards, Kevin

**Comment by asiermarzo** [comment]
Things seems to work now
