### ISSUE TITLE
DriverNano16

### ISSUE THREAD

**Issue by vrossbach** [asiermarzo/Ultraino#3]
I am trying to upload the code for DriverNano16 in the Arduino Uno and this error messages appear:

'class HardwareSerial' has no member named '_dataAvailable'
'class HardwareSerial' has no member named '_peekData'

I tried to put the functions Serial.available() and Serial.peek() but then there is a error to compile to Arduino Uno board. Is there a different code for Arduino Uno or the code was written in another version?

Thank you!

**Comment by asiermarzo** [comment]
Try the instructions on https://github.com/asiermarzo/Ultraino/blob/master/Arduino%20MEGA%2064%20driver%20board%20code/readme.txt

Best

**Comment by vrossbach** [comment]
Hi, 

now I got, I had not pasted the code in the correct public position.

Thank you!
