### ISSUE TITLE
Arbitrary Field Synthesis 

### ISSUE THREAD

**Issue by lolz0r** [asiermarzo/Ultraino#4]
Hi, 
I am curious if there exists a means to create wave-fields of arbitrary shape such that a wide variety of particles can be suspended at the same time. 

My idea is to create an 'acoustic sculpture' where water or perhaps dust is suspended and trapped by the system, and overall comes together to make interesting shapes. 

In sci-fy: https://youtu.be/xNLtPLFECNw?t=53 ... ;)

I imagine the more complex the shape, the larger number of transducers?

Michael

**Comment by asiermarzo** [comment]
That is a cool idea, kindly send an email to asier.marzo@unavarra.es , we are working on a similar project.

Best,
Asier.
